### PR TITLE
🐛 Fix setting folder S3 on etcd backups

### LINKED ISSUE #499: [SURE-9588] Issue setting folder S3 on etcd backups
Hi,
We are trying to configure the etcd backup using S3 bucket parameters in the RKE2ControlPlane manifest:

```
  etcd:
      backupConfig:
        retention: "10"
        scheduleCron: "*/3 * * * *"
        s3:
          bucket: backups-rancher
          endpoint: test-rancher.com
          folder: backup
          enforceSslVerify: true
          s3CredentialSecret:
            apiVersion: v1
            kind: Secret
            namespace: rke2test
            name: creds-etcd-backup
```

The problem is the next part of the code: 

https://github.com/rancher/cluster-api-provider-rke2/blob/3d7df660eddfe972f8135eefb21b6411c9c29124/pkg/rke2/config.go#L322

If I use that s3 folder, I get "directory does not exist" message from rke2-server service because that folder does not exist on the machine for etcd backup, but it exists in my bucket.

The parameter ``folder`` should be independent from the ``EtcdSnapshotDir.``

Thanks

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #499 
~Reverts: https://github.com/rancher/cluster-api-provider-rke2/commit/261395ea390109e7fa4637f4f15261675dfbc08e~

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

File: pkg/rke2/config.go [hunk 1]
```diff
@@ -319,16 +319,13 @@ func newRKE2ServerConfig(opts ServerConfigOpts) (*ServerConfig, []bootstrapv1.Fi
 			})
 		}
 
-		rke2ServerConfig.EtcdSnapshotDir = opts.ServerConfig.Etcd.BackupConfig.S3.Folder
-		rke2ServerConfig.EtcdS3SkipSslVerify = !opts.ServerConfig.Etcd.BackupConfig.S3.EnforceSSLVerify
-	} else {
 		rke2ServerConfig.EtcdSnapshotDir = opts.ServerConfig.Etcd.BackupConfig.Directory
+		rke2ServerConfig.EtcdSnapshotName = opts.ServerConfig.Etcd.BackupConfig.SnapshotName
+		rke2ServerConfig.EtcdSnapshotRetention = opts.ServerConfig.Etcd.BackupConfig.Retention
+		rke2ServerConfig.EtcdSnapshotScheduleCron = opts.ServerConfig.Etcd.BackupConfig.ScheduleCron
```
[the remark this answers is not in the document]
Comment (furkatgofurov7) [reply pkg/rke2/config.go:325]: @Danil-Grigorev yes that is true, however I was making a full revert just in case and prevent further unexpectations.

File: pkg/rke2/config.go [hunk 2]
```diff
@@ -319,16 +319,13 @@ func newRKE2ServerConfig(opts ServerConfigOpts) (*ServerConfig, []bootstrapv1.Fi
 			})
 		}
 
-		rke2ServerConfig.EtcdSnapshotDir = opts.ServerConfig.Etcd.BackupConfig.S3.Folder
```
Comment (alexander-demicev) [inline pkg/rke2/config.go:322]: will only removing this line solve the issue? or as @Danil-Grigorev says about other values, it can be populated anyway

**Comment by alexander-demicev** [comment]
@furkatgofurov7 will the revert cause a regression? AFAIK https://github.com/rancher/cluster-api-provider-rke2/pull/264 addressed a bug we saw when testing etcd restore POC

File: pkg/rke2/config.go [hunk 3]
```diff
@@ -321,12 +321,10 @@ func newRKE2ServerConfig(opts ServerConfigOpts) (*ServerConfig, []bootstrapv1.Fi
...
 		rke2ServerConfig.EtcdS3SkipSslVerify = !opts.ServerConfig.Etcd.BackupConfig.S3.EnforceSSLVerify
-	} else {
-		rke2ServerConfig.EtcdSnapshotDir = opts.ServerConfig.Etcd.BackupConfig.Directory
```
Comment (furkatgofurov7) [inline pkg/rke2/config.go:327]: @alexander-demicev @Danil-Grigorev thanks for reviews, PTAL once again. I updated the code so that `EtcdSnapshotDir` (local snapshot dir) set to `S3.Folder` logic is removed and it being set in else moved out of it since else condition is redundant here.

**Review by alexander-demicev — APPROVED** [review]
